"""Les sept niveaux de Sept Vies.

NE PAS EDITER A LA MAIN : ce fichier est produit et verifie par
outils/genere_niveaux.py. C est la-bas qu on modifie un niveau.
"""

NIVEAUX = [
    {
        "titre": 'Salon, 20h : encore les memes croquettes',
        "maitre": 'le daron',
        "aide": 'Le sac de croquettes est tout en haut. Fais-le tomber dans la gamelle.',
        "message_mort": 'Etouffe avec les croquettes. Une vie de moins, une maison de plus.',
        "message_piege": 'Le sac se renverse dans la gamelle. Les croquettes du fond, celles qui sentent.',
        "carte": [
            "######################",
            "#.........O.....www..#",
            "#.9......===....www..#",
            "#...cc...............#",
            "#......===..........f#",
            "#...................f#",
            "#...===......pp.....f#",
            "#333.........pp.444..#",
            "#333.22......pp.44455#",
            "#333j228C..61pp.44455#",
            "######################",
        ],
        "faux_pieges": {'j': {'declenchement': 'contact', 'recharge': 6.0, 'texte': 'Saute d aussi haut que tu veux : il retombe sur ses pattes.'}},
    },
    {
        "titre": 'La vieille demeure : cent chats, une gamelle',
        "maitre": 'la vieille',
        "aide": 'Fais basculer l arbre a chat du haut du vaisselier, et place-toi dessous.',
        "message_mort": 'Ecrase sous l arbre a chat. Personne n a rien vu.',
        "message_piege": 'L arbre a chat penche. Cent chats regardent ailleurs.',
        "carte": [
            "######################",
            "#........O...........#",
            "#.......===........9.#",
            "#................cc..#",
            "#f.........===.......#",
            "#f...................#",
            "#f...pp.......===...k#",
            "#444.pp...........333#",
            "#444.pp.........22333#",
            "#444lpp18.v.C6..22333#",
            "######################",
        ],
        "faux_pieges": {'k': {'declenchement': 'contact', 'recharge': 8.0, 'effet': 'projection', 'vitesse': (-9, 14), 'texte': 'Un autre chat le pousse dans le vide. Les coussins l attendaient.'}, 'v': {'declenchement': 'action', 'texte': 'La charentaise s abat sur lui. Epaisse comme un matelas. Rien.'}, 'l': {'declenchement': 'action', 'effet': 'soin', 'texte': 'Range dans le buffet avec le linge. Il ressort par en bas, plie, vivant.'}},
    },
    {
        "titre": 'La chambre de l enfant riche',
        "maitre": 'l enfant',
        "aide": 'Le jouet de bain est au sommet du baldaquin. Fais-le tomber dans l aquarium.',
        "message_mort": 'Noye dans l aquarium. Elle croira a un jeu.',
        "message_piege": 'L aquarium deborde. L eau est froide.',
        "carte": [
            "######################",
            "#..O..........www....#",
            "#.===..9......www....#",
            "#........cc..........#",
            "#.===................#",
            "#....................#",
            "#.===.......pp.......#",
            "#........333pp444....#",
            "#.22.....333pp444.55.#",
            "#.22.1.Ce333pp444m556#",
            "######################",
        ],
        "faux_pieges": {'e': {'declenchement': 'contact', 'recharge': 9.0, 'effet': 'projection', 'vitesse': (4, 19), 'texte': 'Attrape et lance en l air facon poupee. Il retombe sur ses pattes. Elle applaudit.'}, 'm': {'declenchement': 'action', 'effet': 'deguisement', 'teinte': (255, 150, 200), 'duree': 5.0, 'texte': 'Maquille, coiffe, deguise. Humiliant. Mais vivant.'}},
    },
    {
        "titre": 'L appart de l influenceur',
        "maitre": 'l influenceur',
        "aide": 'La ring light est perchee la-haut. Son cable traine juste dessous.',
        "message_mort": 'Electrocute en direct. Trois cent mille vues.',
        "message_piege": 'Le cable est denude. Il gresille.',
        "carte": [
            "######################",
            "#......O.......www...#",
            "#.9...===......www...#",
            "#..cc................#",
            "#........===.........#",
            "#....................#",
            "#.....===............#",
            "#333...........444...#",
            "#333.....22....44455.#",
            "#333.18..22.Cn644455g#",
            "######################",
        ],
        "faux_pieges": {'g': {'declenchement': 'action', 'effet': 'projection', 'vitesse': (-3, 15), 'texte': 'Il grimpe au mur pour s echapper. Glisse. Retombe. Story instantanee.'}, 'n': {'declenchement': 'action', 'texte': 'Il mange la plante pour s empoisonner. La vomit. Vivant, et pas fier.'}},
    },
    {
        "titre": 'La cuisine du restaurant, en plein rush',
        "maitre": 'le chef',
        "aide": 'La marmite bout sans surveillance. Fais tomber le couvercle, et saute.',
        "message_mort": 'Tombe dans l eau bouillante. Le service continue.',
        "message_piege": 'La marmite est ouverte. Personne ne regarde.',
        "carte": [
            "######################",
            "#..............O.....#",
            "#.............===..9.#",
            "#....cc..............#",
            "#.........===........#",
            "#....................#",
            "#pp...===............#",
            "#pp................44#",
            "#pp22.......55.....44#",
            "#pp22.C.8.h655u..1.44#",
            "######################",
        ],
        "faux_pieges": {'u': {'declenchement': 'action', 'texte': 'Le couteau bascule du plan de travail... et se plante a cote. Rate.'}, 'h': {'declenchement': 'action', 'texte': 'Provoque, le chef s ecroule : crise cardiaque. Il n aura pas le temps de le tuer.'}},
    },
    {
        "titre": 'Le cabinet medical',
        "maitre": 'le docteur',
        "aide": 'Le flacon d anesthesiant est en haut. Endors le medecin d abord, sinon il soigne tout.',
        "message_mort": 'Cette fois, personne n est venu recoudre.',
        "message_piege": 'Le medecin s est endormi sur son bureau.',
        "carte": [
            "######################",
            "#.www....O...........#",
            "#.www.9.===..........#",
            "#....cc..............#",
            "#..........===.......#",
            "#....................#",
            "#.............===..pp#",
            "#.444..............pp#",
            "#.44455..........22pp#",
            "#.4445518.s.q6.Cd22pp#",
            "######################",
        ],
        "faux_pieges": {'s': {'declenchement': 'action', 'effet': 'soin', 'texte': 'Le scalpel. Precis. Le medecin le recoud en huit minutes, montre en main.'}, 'q': {'declenchement': 'action', 'effet': 'soin', 'texte': 'La seringue du medecin. Reanime. Et vaccine, en prime.'}, 'd': {'declenchement': 'action', 'effet': 'soin', 'texte': 'Il leche le patient contagieux. Gueri en une nuit. Ce medecin est trop fort.'}},
    },
    {
        "titre": 'Le jardin : il ne veut plus mourir',
        "maitre": 'la famille',
        "aide": 'Cette fois il faut rentrer vivant. Evite le bassin. Ils t attendent en haut, a droite.',
        "message_mort": 'Pas comme ca. Pas maintenant. On recommence.',
        "survivre": True,
        "reflexes_coupes": ['moustaches'],
        "cause_mortelle": 'l eau du bassin',
        "carte": [
            "######################",
            "#.www.............G..#",
            "#.www..........===.9.#",
            "#.....cc.............#",
            "#..........===.......#",
            "#....................#",
            "#......===...........#",
            "#33..................#",
            "#33.22...y...........#",
            "#33622.C..XXX.z.XX..6#",
            "######################",
        ],
        "faux_pieges": {'y': {'declenchement': 'contact', 'recharge': 10.0, 'texte': 'Un papillon. Il le suit des yeux. Le bassin est juste la. Pas cette fois.'}, 'z': {'declenchement': 'action', 'texte': 'Une balle de laine. Non. Il sait exactement comment ca finit.'}},
    },
]
