"""Les sept niveaux : la meme maison, sept antagonistes.

Chaque niveau pose ses acteurs dans la maison peinte (game/maison.py) :
``depart``, ``objet`` (ce qu'on pousse), ``piege`` (ou il doit tomber), les
``faux_pieges`` et, au dernier niveau, la ``sortie``. Une position est une
ancre nommee de maison.ANCRES ou un couple (x, y) en pixels de l'image.
"""

NIVEAUX = [
    dict(
        titre="Salon, 20h : escalade jusqu au distributeur", maitre="le daron",
        famille='Le daron et sa femme', probleme='Croquettes tous les soirs, matchs de foot hurles',
        aide="Rebondis d etagere en etagere en gobant les sacs, jusqu au gros distributeur tout en haut. Gave-toi.",
        doodle=True,
        message_piege="Le distributeur deverse sans fin. Le ventre se tend, le ventre se tend...",
        message_mort="Trop de croquettes d un coup. Une vie de moins, une maison de plus.",
        message_attente="Encore un peu de place dans ce petit ventre. Continue.",
        depart="salon",
        # mode Doodle Jump : la tour d etageres, les sacs de croquettes et le
        # distributeur sont generes dans jeu._generer_doodle (rien a poser ici).
    ),
    dict(
        titre="La vieille demeure : cent chats, un chat noir", maitre="la vieille",
        famille='La vieille aux cent chats', probleme='Cent chats, une seule gamelle, rien a soi',
        aide="Un chat noir t attend tout en haut. Rejoins-le malgre la nuee, et fais E.",
        message_piege="",
        message_mort="Le chat noir cligne des yeux. Une vie s en va, doucement.",
        message_attente="",
        depart="salon",
        perso=dict(image="mamie", pos="cuisine"),
        chat_noir="paniere",
        pousseurs=[
            dict(min="canape", max="tv", vitesse=2.6, force=27),
            dict(min="cuisine", max="salon", vitesse=2.2, force=25),
            dict(min="sdb", max="chatterie", vitesse=2.4, force=28),
            dict(min="planche_milieu_g", max="planche_milieu_d", vitesse=3.0, force=28),
            dict(min="chambre", max="couloir", vitesse=2.8, force=26),
            dict(min="salle_droite", max="gamelle_bas", vitesse=2.4, force=25),
            dict(min="arbre_bas", max="arbre_haut", vitesse=2.0, force=24),
            dict(min="planche_salon", max="planche_centre", vitesse=2.6, force=26),
            # la nuee : une foule de chats qui bousculent tres fort
            dict(min=(60, 830), max=(520, 830), vitesse=2.0, force=19),
            dict(min=(620, 830), max=(1080, 830), vitesse=2.28, force=21),
            dict(min=(1150, 830), max=(1500, 830), vitesse=2.56, force=23),
            dict(min=(1520, 830), max=(1720, 830), vitesse=2.84, force=25),
            dict(min=(60, 600), max=(470, 600), vitesse=3.12, force=19),
            dict(min=(560, 600), max=(1040, 600), vitesse=2.0, force=21),
            dict(min=(1120, 600), max=(1500, 600), vitesse=2.28, force=23),
            dict(min=(1520, 600), max=(1720, 600), vitesse=2.56, force=25),
            dict(min=(60, 300), max=(500, 300), vitesse=2.84, force=19),
            dict(min=(620, 300), max=(1080, 300), vitesse=3.12, force=21),
            dict(min=(1160, 300), max=(1500, 300), vitesse=2.0, force=23),
            dict(min=(1520, 300), max=(1700, 300), vitesse=2.28, force=25),
            dict(min=(130, 380), max=(300, 380), vitesse=2.56, force=19),
            dict(min=(560, 380), max=(760, 380), vitesse=2.84, force=21),
            dict(min=(700, 250), max=(900, 250), vitesse=3.12, force=23),
            dict(min=(900, 480), max=(1120, 480), vitesse=2.0, force=25),
            dict(min=(1180, 380), max=(1400, 380), vitesse=2.28, force=19),
            dict(min=(620, 620), max=(820, 620), vitesse=2.56, force=21),
            dict(min=(1200, 700), max=(1420, 700), vitesse=2.84, force=23),
            dict(min=(1480, 480), max=(1680, 480), vitesse=3.12, force=25),
            dict(min=(300, 620), max=(480, 620), vitesse=2.0, force=19),
        ],
        faux_pieges={
            "k": dict(pos="arbre_bas", declenchement="contact", recharge=9.0,
                      effet="projection", vitesse=(-9, 14), image="chat_gris",
                      texte="Un autre chat le pousse dans le vide. Les coussins l attendaient."),
            "v": dict(pos="cuisine", declenchement="action", image="vieille",
                      texte="La charentaise s abat sur lui. Epaisse comme un matelas. Rien."),
            "l": dict(pos="chambre", declenchement="action", effet="soin", image="panier_linge",
                      texte="Range dans le buffet avec le linge. Il ressort par en bas, plie, vivant."),
            "c": dict(pos="sdb", declenchement="action", image="verre_casse",
                      texte="Il marche sur un vieux bocal casse. La vieille le desinfecte aussitot."),
            "b": dict(pos="salle_droite", declenchement="action", image="bougie",
                      texte="Il approche une bougie. La vieille souffle dessus en passant. Perdu."),
        },
    ),
    dict(
        titre="La chambre de l enfant riche", maitre="l enfant",
        famille='Les parents riches', probleme='Confie a leur petite fille insupportable',
        aide="L aquarium est en haut a droite. Rejoins-le et fais E -- mais la petite te poursuit et te rejette sans cesse.",
        message_piege="",
        message_mort="Noye dans l aquarium. Elle croira a un jeu.",
        message_attente="",
        depart="salon",
        piege="aquarium", piege_image="aucune", piege_largeur=120, piege_direct=True, libelle_piege="Se noyer dans l aquarium",
        fille="salle_droite",
        pousseurs=[
            dict(min="frigo", max="planche_centre", vitesse=2.6),
            dict(min="chatterie", max="planche_milieu_d", vitesse=2.8, force=17),
        ],
        faux_pieges={
            "e": dict(pos="chambre", declenchement="contact", recharge=9.0,
                      effet="projection", vitesse=(4, 19), image="enfant",
                      texte="Attrape et lance en l air facon poupee. Il retombe sur ses pattes. Elle applaudit."),
            "m": dict(pos="couloir", declenchement="action", effet="deguisement",
                      image="maquillage", teinte=(255, 150, 200), duree=5.0,
                      texte="Maquille, coiffe, deguise. Humiliant. Mais vivant."),
            "l": dict(pos="lit", declenchement="contact", recharge=8.0, image="lit_baldaquin",
                      effet="toupie", duree=1.2,
                      texte="Il vacille au bord du lit a baldaquin, tourne sur lui-meme... et se rattrape."),
            "f": dict(pos="chatterie", declenchement="action", image="fenetre_ouverte",
                      texte="Il se jette de la fenetre. Atterrit dans le bac a jouets. Mou."),
            "d": dict(pos="salle_droite", declenchement="action", image="cordelette",
                      texte="Il s emmele dans le fil dentaire de l enfant. Elle le delivre en riant."),
        },
    ),
    dict(
        titre="L appart de l influenceur", maitre="l influenceur",
        famille='L influenceur', probleme='Filme non-stop pour des videos nulles',
        aide="L influenceur te filme (le cadre carre, visible sur son ecran). Sors de son champ, rejoins le cable, et fais E. Dans le champ, il te sauve.",
        message_piege="Le cable est denude. Il gresille.",
        message_mort="Electrocute en direct. Trois cent mille vues.",
        message_attente="Le cable est encore bien range. Fais tomber la ring light.",
        depart="salon",
        perso=dict(image="influenceur", pos="salon"),
        piege=(1540, 270), piege_image="aucune", piege_anime="cable_anime", piege_largeur=130, piege_direct=True, camera=True, libelle_piege="Se prendre dans le cable",
        pousseurs=[
            dict(min="cuisine", max="salle_droite", vitesse=3.0, force=18),
            dict(min="planche_milieu_g", max="planche_milieu_d", vitesse=2.8),
        ],
        faux_pieges={
            "g": dict(pos="cuisine", declenchement="action", effet="projection",
                      vitesse=(3, 15), image="griffures",
                      texte="Il grimpe au mur pour s echapper. Glisse. Retombe. Story instantanee."),
            "n": dict(pos="salle_droite", declenchement="action", image="poison",
                      texte="Il mange la plante pour s empoisonner. La vomit. Vivant, et pas fier."),
            "p": dict(pos="tv", declenchement="action", image="prise",
                      texte="Il mord une multiprise de tournage. Disjoncte. L influenceur peste."),
            "w": dict(pos="chambre", declenchement="action", image="fenetre_ouverte",
                      texte="Il saute par la fenetre de l appart. Un auvent le rattrape. Content en bas."),
        },
    ),
    dict(
        titre="La cuisine du restaurant, en plein rush", maitre="le chef",
        famille='Personne : la rue', probleme='Sans toit, sans maitre, attire par les cuisines',
        aide="Des piments partout ! Devore-les le plus vite possible pour vider ta barre de vie avant qu elle ne remonte.",
        message_piege="La barre est a zero. Trop de piment pour un si petit chat.",
        message_mort="Le palais en feu, le chat s effondre. Neuf epices, une vie de moins.",
        message_attente="Ta barre de vie remonte. Mange les piments plus vite !",
        depart="salon",
        # mini-jeu : engloutir les piments (qui repoussent) pour vider la barre de vie
        piments=[
            "cuisine", "salon", "salle_droite", "canape", "tv", "frigo",
            "sdb", "chatterie", "planche_sdb", "planche_centre",
            "planche_milieu_g", "planche_milieu_d", "planche_salon",
            "chambre", "couloir", "armoire", "salle_haut", "gamelle_bas",
        ],
    ),
    dict(
        titre="Le cabinet medical", maitre="le docteur",
        famille='Le veterinaire', probleme='Bete de foire du cabinet, soigne de force',
        aide="Des que tu tentes de mourir, il accourt te recoudre. Endors-le avec les somniferes (au-dessus de lui), puis file te tuer avant qu il ne se releve.",
        message_piege="Les somniferes tombent sur le medecin. Il glisse. Il ronfle... pour un moment.",
        message_mort="Cette fois, personne n est venu recoudre.",
        message_attente="Le medecin veille (aura rouge). Endors-le d abord avec les somniferes.",
        depart="salon", docteur=True,
        pousseurs=[
            dict(min="salon", max="tv", vitesse=2.2),
        ],
                piege="planche_centre", piege_image="aucune", piege_largeur=200, piege_hauteur=4,
        faux_pieges={
            "so": dict(pos=(880, 434), declenchement="action", effet="endort",
                       image="somniferes", texte="Tu renverses les somniferes sur le medecin. Il s endort."),
            "s": dict(pos="frigo", declenchement="action", effet="soin",
                      image="scalpel", cause="le scalpel",
                      texte="Le scalpel. Precis. Le medecin le recoud en huit minutes, montre en main."),
            "q": dict(pos="planche_milieu_d", declenchement="action", effet="soin",
                      image="seringue", cause="la seringue du medecin",
                      texte="La seringue du medecin. Reanime. Et vaccine, en prime."),
            "t": dict(pos="couloir", declenchement="action", effet="soin",
                      image="defibrillateur", cause="le defibrillateur",
                      texte="Il mord les palettes du defibrillateur. Le medecin le relance d un coup de machine."),
            "a": dict(pos="cuisine", declenchement="action", effet="soin",
                      image="medicaments", cause="l armoire a pharmacie",
                      texte="Il avale la moitie de l armoire a pharmacie. Lavage d estomac. Encore rate."),
            "d": dict(pos="chambre", declenchement="action", effet="soin",
                      image="patient", cause="la maladie du patient",
                      texte="Il leche le patient contagieux. Gueri en une nuit. Ce medecin est trop fort."),
            "z": dict(pos="salle_droite", declenchement="action", effet="soin",
                      image="poison", cause="le flacon de morphine",
                      texte="Il lape la morphine du medecin. Naloxone, oxygene. Sauve, encore."),
        },
    ),
    dict(
        titre="Chez lui : il ne veut plus mourir", maitre="la famille",
        famille='La bonne famille, enfin', probleme='Aucun. Et c est ca, le probleme',
        aide="Cette fois il faut rentrer vivant. Evite les guirlandes de la fete. Ils t attendent pres de la paniere, a l etage.",
        message_mort="Pas comme ca. Pas maintenant. On recommence.",
        survivre=True, reflexes_coupes=["moustaches"],
        depart="salon",
        perso=dict(image="couple", pos="salon"),
        pousseurs=[
            dict(min="canape", max="tv", vitesse=2.6),
            dict(min="chambre", max="couloir", vitesse=2.2),
        ],
        sortie="paniere",
        mortels=[
            dict(pos="planche_centre", image="cable", cause="la guirlande electrique"),
            dict(pos="couloir", image="cable", cause="la guirlande electrique"),
        ],
        faux_pieges={
            "y": dict(pos="planche_milieu_g", declenchement="contact", recharge=10.0,
                      image="papillon",
                      texte="Un papillon. Il le suit des yeux. La guirlande est juste la. Pas cette fois."),
            "z": dict(pos="canape", declenchement="action", image="pelote",
                      texte="Une balle de laine. Non. Il sait exactement comment ca finit."),
            "b": dict(pos="salle_droite", declenchement="action", image="bougie",
                      texte="Une bougie de la fete. Il s ecarte. Il tient trop a ce soir."),
        },
    ),
]
